# Generated by Django 3.2.6 on 2021-08-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Last_login_time',
        ),
    ]
