# Generated by Django 3.2.6 on 2021-08-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_count',
            field=models.IntegerField(default=1),
        ),
    ]
