# Generated by Django 3.2.6 on 2021-08-02 19:35

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_User', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
                ('Post_name', models.CharField(max_length=30)),
                ('Post_Tags', models.CharField(max_length=50)),
                ('Post_Contents', models.CharField(max_length=200)),
                ('Post_Timestamps', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
