# Generated by Django 3.2.6 on 2021-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_posts_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Post_Contents',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Post_Tags',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Post_User',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Post_name',
            field=models.CharField(max_length=500),
        ),
    ]
